"""Constants for the Enki Home Assistant integration."""

from logging import Logger, getLogger

LOGGER: Logger = getLogger(__package__)

DOMAIN = "enki"
NAME = "Enki"

CONF_SCAN_INTERVAL = "scan_interval"
CONF_TELEMETRY = "telemetry"
CONF_TELEMETRY_ONBOARDING = "telemetry_onboarding_shown"

DEFAULT_SCAN_INTERVAL = 30
MIN_SCAN_INTERVAL = 10
MAX_SCAN_INTERVAL = 300

ENKI_OIDC_URL = "https://keycloak-prod.iot.leroymerlin.fr/realms/enki/protocol/openid-connect/token"
ENKI_BASE_URL = "https://enki.api.devportal.adeo.cloud"
ENKI_USER_AGENT = "Enki/2.25.1 (iPhone; iOS 18.0; Scale/3.00) Enki"

# Gateway API keys (reverse-engineered from the Enki mobile app traffic).
# They may change when the app updates — see docs/API.md.
ENKI_HOME_API_KEY = "FULsxyI3x1f7MtLVOsP6V1DeAPmBQJCB"
ENKI_BFF_API_KEY = "Bco7qBHRHOQiSVcEHdgS0rijpebMBwkB"
ENKI_NODE_API_KEY = "UBb0Kv6xXpG6bOvD8VZ9A63uxqQ4G1A3"
ENKI_REFERENTIEL_API_KEY = "3uk9rlaIUgBsz1tEPV7GQMhhGfRwPFJY"
ENKI_LIGHTS_API_KEY = "3OVsNulRsUXfr7Hze54OHx8l6qDu2UcE"
ENKI_POWER_API_KEY = "PCnbndkIqlfXwXGhFkqSWWMn4HcWza9J"
ENKI_AIRFLOW_API_KEY = "L7nSeH7MOgxOCz0HpysKmOI3PQMM8SDV"
ENKI_TEMPERATURE_HUMIDITY_API_KEY = "5Oqfse9MTtAWdfxwhlSPrOVO4gwqfgku"
ENKI_BATTERY_HEALTH_API_KEY = "4o6CgR2B5fsq8eJw3VUk1GDs02Y6zKO3"
ENKI_PRESENCE_DETECTOR_API_KEY = "b5A3sQcYHpRta3SqGXwH9T9GNaNHpj96"
ENKI_CONTACT_SENSOR_API_KEY = "YlTcpTzG8Fm2z52MN89laCGnCx6ldbWx"
ENKI_SIREN_API_KEY = "DKHq99GEVf2F3r32QGXefPX0B5cuJ9PV"

# api-enki-heating-prod (pilot wire, Noirot/ACOVA radiators, …).
ENKI_HEATING_API_KEY = "ci2ml5gZ0AghnE9Pdc6fqGloz7GQnlRA"

# api-enki-water-leak-detector-prod (Lexman leak detectors, …).
ENKI_WATER_SENSOR_API_KEY = "TZckkGN2S5wHuImS8BSdJ9dfuTfDxgHi"

FAN_ENDPOINT = 1
LIGHT_ENDPOINT = 2

AIRFLOW_MODE_MANUAL = "MANUAL"
AIRFLOW_MODE_BREEZE = "BREEZE"

PRESET_MODE_MANUAL = "manual"
PRESET_MODE_BREEZE = "breeze"

# Blade rotation (api-enki-airflow-prod; check/change-fan-rotation-direction).
AIRFLOW_ROTATION_CLOCKWISE = "CLOCKWISE"
AIRFLOW_ROTATION_COUNTERCLOCKWISE = "COUNTERCLOCKWISE"

DIRECTION_FORWARD = "forward"
DIRECTION_REVERSE = "reverse"

DEVICE_TYPE_LIGHTS = "lights"
DEVICE_TYPE_FANS = "ceiling_fans"
DEVICE_TYPE_INVERTERS = "inverters"
DEVICE_TYPE_ACCESS_MOTORIZATION = "access_and_motorizations"
DEVICE_TYPE_SENSORS = "sensors"

# api-enki-rolling-prod (roller shutters — paths shutter/{nodeId}/…, APK 2.25.1+).
ENKI_ACCESS_MOTORIZATION_API_KEY = "QegWuQR3zSKLlJZ2OITv94vjtSaaPkDp"

# --- Future micro-services (APK 2.25.1, pre-registered — see api/gateway_registry.py) ---
ENKI_ALEXA_MAPPER_API_KEY = "BE0IG8yArB30vKf2sRK3b7B4CCzPKKp2"
ENKI_AVIDSEN_THERMOSTAT_API_KEY = "fFgGBdPnmCPgu5ouGylYtu7iLLtm5Q6x"
ENKI_BLUETOOTH_API_KEY = "PYURMrg9ebWptHbIadq2MVJhX53ivnqM"
ENKI_BOILER_SYSTEM_API_KEY = ""
ENKI_COACH_ENERGY_API_KEY = ""
ENKI_COMMAND_OVERRIDE_API_KEY = "ffm1enzaqMPG9rVCz2J0kX0sIqAGMB6m"
ENKI_CONSENT_API_KEY = "fFgGBdPnmCPgu5ouGylYtu7iLLtm5Q6x"
ENKI_CONSUMPTION_API_KEY = "BE0IG8yArB30vKf2sRK3b7B4CCzPKKp2"
ENKI_COUNTRY_API_KEY = "XEcosERU3GeCfXCwKOLMKFI80DMnG861"
ENKI_DIAGRAL_API_KEY = "BE0IG8yArB30vKf2sRK3b7B4CCzPKKp2"
ENKI_DIO_API_KEY = "YlTcpTzG8Fm2z52MN89laCGnCx6ldbWx"
ENKI_ENEDIS_API_KEY = ""
ENKI_ENERGY_PRODUCTION_API_KEY = "Cs4FTurpjhst7FUKMNMNGnWYCp0F2F5o"
ENKI_ENERGY_SUBSCRIPTION_API_KEY = ""
ENKI_ENOCEAN_API_KEY = "ZMPwufU2eBifcyAHaEAfEL2FvUkdGSZi"
ENKI_EQUATION_AIRCO_API_KEY = ""
ENKI_EQUATION_WATER_HEATER_API_KEY = "ci2ml5gZ0AghnE9Pdc6fqGloz7GQnlRA"
ENKI_ESDK_API_KEY = "RSXHvuEl2Dz9hgbJ2BeuPqO9OcIv4f27"
ENKI_GROUP_API_KEY = "ci2ml5gZ0AghnE9Pdc6fqGloz7GQnlRA"
ENKI_GW_CONNECT_API_KEY = "1B61R4biYqnq60c5UFWQA5fxnDwLFEG6"
ENKI_GW_ESSENTIELB_API_KEY = ""
ENKI_GW_V1_API_KEY = ""
ENKI_HEATING_CONTROLLER_API_KEY = ""
ENKI_HOME_SECURITY_API_KEY = "Ix4f2dYPTJ6ztKnrYmcFSe52HhSH6Xzu"
ENKI_LEROY_MERLIN_API_KEY = "ci2ml5gZ0AghnE9Pdc6fqGloz7GQnlRA"
ENKI_LEXMAN_CAMERA_MEARI_API_KEY = "ffm1enzaqMPG9rVCz2J0kX0sIqAGMB6m"
ENKI_LEXMAN_CAMERA_API_KEY = "t0s9EFyVcggLp8FxImoaaxZWBCbQGztz"
ENKI_LEXMAN_CHARGEPOINT_API_KEY = "L9RRFgbJuvTgW0ZI03mQMTNtND8mzAUa"
ENKI_LEXMAN_ENVERTECH_API_KEY = "HMGJVJ3f1K4pfr5h95ycgOixz6MKtPXF"
ENKI_LIGHTING_REMOTE_CONTROL_API_KEY = "PCnbndkIqlfXwXGhFkqSWWMn4HcWza9J"
ENKI_LOGBOOK_API_KEY = "ffm1enzaqMPG9rVCz2J0kX0sIqAGMB6m"
ENKI_LUMINOSITY_SENSOR_API_KEY = "fFgGBdPnmCPgu5ouGylYtu7iLLtm5Q6x"
ENKI_MOBILE_CONFIG_API_KEY = "ffm1enzaqMPG9rVCz2J0kX0sIqAGMB6m"
ENKI_MOBILE_HEATING_BFF_API_KEY = ""
ENKI_MOBILE_PAIRING_WORKFLOW_API_KEY = "QegWuQR3zSKLlJZ2OITv94vjtSaaPkDp"
ENKI_NETATMO_API_KEY = "0waXGEuJoXr0KTOKc1yDMEDuXODnFc9r"
ENKI_OTA_API_KEY = "QegWuQR3zSKLlJZ2OITv94vjtSaaPkDp"
ENKI_PAYMENT_API_KEY = ""
ENKI_PHILIPS_API_KEY = "rJT7W4mANrf7bh5pFiVk963i8dFVEUBy"
ENKI_PRODUCT_HIGHLIGHT_API_KEY = "QegWuQR3zSKLlJZ2OITv94vjtSaaPkDp"
ENKI_PROGRAMMER_API_KEY = "PCnbndkIqlfXwXGhFkqSWWMn4HcWza9J"
ENKI_ROOM_API_KEY = "BXY9qWUEoGiAI5phZAc1oJa8LgiJm0is"
ENKI_RTS_API_KEY = ""
ENKI_SAUTER_API_KEY = "PCnbndkIqlfXwXGhFkqSWWMn4HcWza9J"
ENKI_SCENARIO_API_KEY = "PCnbndkIqlfXwXGhFkqSWWMn4HcWza9J"
ENKI_SCHEDULE_API_KEY = "PCnbndkIqlfXwXGhFkqSWWMn4HcWza9J"
ENKI_SMOKE_DETECTOR_API_KEY = "0lMCF6VlYjC1TKsbHLgQkNrbwsfQ69wz"
ENKI_SOMFY_API_KEY = "spMWKQGYAPBGFwsVhRjF1rPd65EdInSM"
ENKI_STATION_METEO_NETATMO_API_KEY = "LqJFYagwqDEZuAfXdTGAXbL1P7Sb4MGM"
ENKI_SURVOLTAGE_API_KEY = "eUpjduUizxGzuq6wYgTomoKBoOlzIWlA"
ENKI_TAHOMA_API_KEY = "zafWVW3o0yvcoteizdxSZWMgIcS57lut"
ENKI_TAPO_API_KEY = "IVVrlDVLGYEiG99KGpXHo7vIsZSLdT5O"
ENKI_THERMOSTAT_API_KEY = ""
ENKI_USER_DATA_AGG_API_KEY = "VmJZYIucXW1cbd5TnSt9TwiX4xOpvzBI"
ENKI_USER_INFORMATION_API_KEY = "eUpjduUizxGzuq6wYgTomoKBoOlzIWlA"
ENKI_USER_PREFERENCES_API_KEY = "3zAlnfKYWvD1A1je7rgu7sktc0lmRBun"
ENKI_USER_API_KEY = "Px5B6M16shAhnSU7uSMTE3x3AgWmky4R"
ENKI_VIDEOPHONE_API_KEY = "ffm1enzaqMPG9rVCz2J0kX0sIqAGMB6m"
ENKI_VIEW_API_KEY = "p39cCbWyFMpQexKGHvwGrsnqdxVlItuq"
ENKI_WIZ_API_KEY = "BzO5Kq2kY6urshzllbsi3nmh84T6ujam"
ENKI_ZIGBEE_API_KEY = "Dkcy4L4oQHZvjMy6cqbkKMQs5VqY9Bbp"

REFERENTIEL_VERSION = "2.23.0"

FAN_SPEED_MIN = 1
FAN_SPEED_MAX = 6
ORDERED_FAN_SPEEDS = list(range(FAN_SPEED_MIN, FAN_SPEED_MAX + 1))

# Device profile sharing (opt-in). See docs/TELEMETRY.md.
TELEMETRY_GITHUB_REPO = "cyrilcolinet/enki-integration-hass"
TELEMETRY_ISSUE_LABELS = ("device-telemetry", "enhancement")
